
server:
  port: 8771

#服务的名称
spring:
  application:
    name: product-service
  cloud:
    client:
      ipAddress: 192.168.31.230
  zipkin:
    base-url: http://192.168.31.210:9411/
  sleuth:
    sampler:
      probability: 1

#指定注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}:${spring.application.name}
env: test
branch: master
